version: "3.8"

services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/deluge:/config
      - ${ROOT}/Downloads:/downloads
    restart: unless-stopped
